### ISSUE TITLE
Implement color printing

### ISSUE THREAD

**Issue by maxeonyx** [araytiay/rand-rhall#8]
add functionality to DynamicPrinter so that it can change the display color of the terminal with tags like &color&

**Comment by araytiay** [comment]
Have implemented (see latest commit). Methods are tacked on to string: more can be added using def <colour_name> and the ansi colour code obtained from http://pueblo.sourceforge.net/doc/manual/ansi_color_codes.html. To add these methods to the dynamic printer as a tag, a unique character identifier (r for red etc.) is added to the col_map hash mapped to the method name. (I know, ugly eval :( )
The tags are written as &<colour_identifier> and are parsed inside the string, for example '&r' flags the following text to be red.

Example string, in which 'world' is red: "Hello &rworld&n"

**Comment by araytiay** [comment]
Current flags:
_note, normal must be used to terminate current effects applied_

| Modifier | Flag |
| --- | --- |
| red | &r |
| blue | &b |
| green | &g |
| yellow | &y |
| bold | &i |
| normal | &n |
| invisible wait | ^ |
| pauses (also prints this char) | . , |
